import axios from 'axios';
import config from './config.js';

 // The default function is used to return api requests regarding the user

export default async (region, username) => {

    const regionApi = axios.create({
        baseURL: 'https://' + region + '.api.riotgames.com/lol',
    });

    //we need the basic info first to get the encrypted id generated by your API Key
    let userBasicInfoResponse = await regionApi.get('/summoner/v4/summoners/by-name/' + username + '?api_key=' + config.api_key);
    let userBasicInfo = userBasicInfoResponse.data;

    //actual profile info
    let userProfileResponse = await regionApi.get('/league/v4/entries/by-summoner/' + userBasicInfo.id + '?api_key=' + config.api_key);
    let userLeague = userProfileResponse.data;
    let avatarURL = `http://ddragon.leagueoflegends.com/cdn/10.11.1/img/profileicon/${userBasicInfo.profileIconId}.png`;
    userBasicInfo.avatarURL = avatarURL;

    //making a single array with all info gotten from both requests
    let allInfo = {...userBasicInfo, leagueInfo: userLeague};

    return allInfo;

} //end of default function

const leagueTypeTranslation = (leagueType) => {

    switch(leagueType){

        case 'RANKED_SOLO_5x5':
            return 'Solo/Duo Queue';

        case 'RANKED_FLEX_SR':
            return 'Flex 5x5 Queue';

        default: 
            return '';

    }

} //end of leagueTypeTranslation

export const checkLeague = (league) => {

    if(league != undefined){

        return  (`${leagueTypeTranslation(league.queueType)}: ${league.tier} ${league.rank} \n` +
                 `Winrate: ${ (league.wins / ( league.wins + league.losses) * 100).toFixed(2) }%  \n\n`);

    }else{

        return '';

    }

} //end of checkLeague