import axios from 'axios';
import config from './config.js';

const brApi = axios.create({
    baseURL: 'https://br1.api.riotgames.com/lol',
});

//summoners/by-name/firewest?api_key=RGAPI-1a6eded8-3d6d-482b-ae67-63332349dcb4

//function start
export default async (username) => {

    //we need the basic info first to get the encrypted id generated by your API Key
    let userBasicInfoResponse = await brApi.get('/summoner/v4/summoners/by-name/' + username + '?api_key=' + config.api_key);
    let userBasicInfo = userBasicInfoResponse.data;

    //actual profile info
    let userProfileResponse = await brApi.get('/league/v4/entries/by-summoner/' + userBasicInfo.id + '?api_key=' + config.api_key);
    let userProfile = userProfileResponse.data;
    let avatarURL = `http://ddragon.leagueoflegends.com/cdn/10.11.1/img/profileicon/${userBasicInfo.profileIconId}.png`;
    userBasicInfo.avatarURL = avatarURL;

    //making a single array with all info gotten from both requests
    let allInfo = {...userBasicInfo, ...userProfile};

    return allInfo;

}