import axios from 'axios';
import config from './config.js';

//function start
export default async (region, username) => {

    const regionApi = axios.create({
        baseURL: 'https://' + region + '.api.riotgames.com/lol',
    });

    //we need the basic info first to get the encrypted id generated by your API Key
    let userBasicInfoResponse = await regionApi.get('/summoner/v4/summoners/by-name/' + username + '?api_key=' + config.api_key);
    let userBasicInfo = userBasicInfoResponse.data;

    //actual profile info
    let userProfileResponse = await regionApi.get('/league/v4/entries/by-summoner/' + userBasicInfo.id + '?api_key=' + config.api_key);
    let userLeague = userProfileResponse.data;
    let avatarURL = `http://ddragon.leagueoflegends.com/cdn/10.11.1/img/profileicon/${userBasicInfo.profileIconId}.png`;
    userBasicInfo.avatarURL = avatarURL;

    //making a single array with all info gotten from both requests
    let allInfo = {...userBasicInfo, leagueInfo: userLeague};

    return allInfo;

}